import { NextResponse } from "next/server";
const data = [
  "stt_cs",
  "stt_cs_gb",
  "stt_cs_gc",
  "stt_cs_gd",
  "stt_cs_ge",
  "stt_cs_gf",
  "stt_cs_review",
  "stt_cs_gb_review",
  "stt_cs_gc_review",
  "stt_cs_gd_review",
  "stt_cs_ge_review",
  "stt_cs_gf_review",
  "stt_tt_ga",
  "stt_tt_gb",
  "stt_tt_gc",
  "stt_tt_gd",
  "stt_tt_ge",
  "stt_tt_gf",
  "stt_tt_gg",
  "stt_tt_gh",
  "stt_tt_ga_review",
  "stt_tt_gb_review",
  "stt_tt_gc_review",
  "stt_tt_gd_review",
  "stt_tt_ge_review",
  "stt_tt_gf_review",
  "stt_tt_gg_review",
  "stt_tt_gh_review",
  "stt_ns_ga",
  "stt_ns_gb",
  "stt_ns_gc",
  "stt_ns_gd",
  "stt_ns_ga_review",
  "stt_ns_gb_review",
  "stt_ns_gc_review",
  "stt_ns_gd_review",
  "stt_ab_ga",
  "stt_ab_gb",
  "stt_ab_ga_review",
  "stt_ab_gb_review",
];
export async function GET() {
  return NextResponse.json({ data });
}
